name: Next Actions
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Move to client dir
        run: cd client/
      - name: Print current dir
        run: pwd
      - name: Install dependencies
        run: npm ci
      - name: Test app
        run: npm run test
