name: Next Actions
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Test app
        working-directory: ./client
        run: npm run test
